### ISSUE TITLE
3x rewards not working

### ISSUE THREAD

**Issue by hazydaze11** [WubbaLubbaDubDubDev/notpixel_bot_advanced#1]
How to enable 3x rewards? Here is no any settings for it :(

**Comment by WubbaLubbaDubDubDev** [comment]
Yes, this issue is caused by the latest update, which changed the game's script structure, specifically the part that contains data about the art that gives a 3x reward for drawing. The parser is currently unable to correctly retrieve this data, so the script is running in 'emergency' mode, drawing random pixels. I'm currently analyzing ways to resolve this problem, so please stay tuned for an update.

**Comment by WubbaLubbaDubDubDev** [comment]
There are no separate settings for the 3x mode, as the current script operated in this mode by default. I'm considering adding an option to enable or disable it in future updates.> How to enable 3x rewards? Here is no any settings for it :(

**Comment by WubbaLubbaDubDubDev** [comment]
> How to enable 3x rewards? Here is no any settings for it :(

There are no separate settings for the 3x mode, as the current script operated in this mode by default. I'm considering adding an option to enable or disable it in future updates.

**Comment by WubbaLubbaDubDubDev** [comment]
> How to enable 3x rewards? Here is no any settings for it :(

![image](https://github.com/user-attachments/assets/2f8b0a35-310a-49be-bdb9-530979d283c1)

Good news, 3x is working again! I would also like to point out that the script doesn't always manage to paint the required pixel first, so sometimes you may see cases where the 3x reward is not obtained.

**Comment by hazydaze11** [comment]
> > How to enable 3x rewards? Here is no any settings for it :(
> 
> ![image](https://private-user-images.githubusercontent.com/48893302/375899899-2f8b0a35-310a-49be-bdb9-530979d283c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2ODYyOTksIm5iZiI6MTcyODY4NTk5OSwicGF0aCI6Ii80ODg5MzMwMi8zNzU4OTk4OTktMmY4YjBhMzUtMzEwYS00OWJlLWJkYjktNTMwOTc5ZDI4M2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDIyMzMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZmU4YjA3M2IxZTBiNzRlZDM1Yzg0Y2FjYTAyNjIzMzU3MDYzNzhhNzg5NDlhY2NmNDZkNWNhODZhYzVmYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Dxr_MqZRy6DxeIfmWALWYFQ5HupkBqM4PioE8yX_D_0)
> 
> Good news, 3x is working again! I would also like to point out that the script doesn't always manage to paint the required pixel first, so sometimes you may see cases where the 3x reward is not obtained.

![111](https://github.com/user-attachments/assets/24a314c5-8ee5-42c7-972a-47237aba4b74)

still 1.0 points

**Comment by hazydaze11** [comment]
Need to update folder "bot"?
