### ISSUE TITLE
error 500 on repaint request

### ISSUE THREAD

**Issue by AKASH-UWU** [WubbaLubbaDubDubDev/notpixel_bot_advanced#10]
![image](https://github.com/user-attachments/assets/09018af8-5b62-4e32-875a-d69b98b07ce3)
is cloudflare blocking the api calls?

**Comment by darkPrince74** [comment]
same issue here without proxy @WubbaLubbaDubDubDev

**Comment by WubbaLubbaDubDubDev** [comment]
> same issue here without proxy @WubbaLubbaDubDubDev 

It seems that the notpixel servers are overloaded. The error code 500 indicates a server-side error that prevented the request from being processed.

**Comment by WubbaLubbaDubDubDev** [comment]
> Well, I tried painting it manually, and it worked that time, so I thought it might have been CF problem. Regardless, it's working again now.

Yes, it's a strange situation, but I have also noticed such behavior before, where images fail to load for unknown reasons, but over time everything falls back into place. In such cases, I recommend disabling the use of random templates, so the script will paint the main template. I'll try to figure out what the problem is.

**Comment by WubbaLubbaDubDubDev** [comment]
> Well, I tried painting it manually, and it worked that time, so I thought it might have been CF problem. Regardless, it's working again now.

I still observe an issue with loading new templates, but now it's not a 500 error but a 400, which isn't good, as it's a client-side problem. So, for now, I recommend setting the parameter USE_UNPOPULAR_TEMPLATE to False.

**Comment by AKASH-UWU** [comment]
I didn’t want to reopen the issue, but it seems the 500 error (repaint) still exists. I’m not sure why, but after adding query_id before user in initData, it seems to work every time. However, in the bot and the Notpx main API, it’s used without user. I don’t know what the problem is.

**Comment by WubbaLubbaDubDubDev** [comment]
> I didn’t want to reopen the issue, but it seems the 500 error (repaint) still exists. I’m not sure why, but after adding query_id before user in initData, it seems to work every time. However, in the bot and the Notpx main API, it’s used without query_id. I don’t know what the problem is.

I have some great news! After investigating how image uploads function in the original application, I found that authorization headers are unnecessary. I tested this by entering the link directly in my browser, and it downloaded flawlessly. Next, I disabled the proxy in my script, and the uploads succeeded, though I occasionally faced 400 or 500 errors. Out of curiosity, I attempted to restructure the uploads using requests, and surprisingly, it works even with the proxy. I’m puzzled as to why aiohttp combined with the proxy generates these errors; it’s still a mystery to me. Stay tuned for updates, as I’m currently testing.

**Comment by WubbaLubbaDubDubDev** [comment]
> I didn’t want to reopen the issue, but it seems the 500 error (repaint) still exists. I’m not sure why, but after adding query_id before user in initData, it seems to work every time. However, in the bot and the Notpx main API, it’s used without query_id. I don’t know what the problem is.

I've added fixes for the script to work correctly. You can update now.

**Comment by AKASH-UWU** [comment]
![image](https://github.com/user-attachments/assets/0f86ab54-4230-43df-a0b8-b9fa14f00cf1)

new tapper.py showing this but old one is working..

**Comment by WubbaLubbaDubDubDev** [comment]
> new tapper.py showing this but old one is working..
Oops, my bad! Looks like I forgot to update the requirements.txt. I’ll sort it out right away 😬

**Comment by WubbaLubbaDubDubDev** [comment]
> 
> new tapper.py showing this but old one is working..

Oops, my bad! Looks like I forgot to update the requirements.txt. I’ll sort it out right away 😬

**Comment by WubbaLubbaDubDubDev** [comment]
@AKASH-UWU

Done, I fixed it! The new update included some libraries that aren't in the standard Python set, and I forgot to add them. Sorry about that, I rushed it. I've tested it in a fresh Docker container, and everything should be working now.

**Comment by AKASH-UWU** [comment]
Damn working better than the previous version 💥.. Thanks bro.
