### ISSUE TITLE
Canvas image load failure

### ISSUE THREAD

**Issue by WubbaLubbaDubDubDev** [WubbaLubbaDubDubDev/notpixel_bot_advanced#15]
I am opening this issue because I've noticed drawing problems during the canvas image loading stage in my bot. I recommend temporarily disabling the drawing feature while I investigate the problem.

**Comment by SeiZ28** [comment]
![image](https://github.com/user-attachments/assets/7f214b0a-64c2-45c1-ac6f-5aa4f9ae2fd2)

**Comment by WubbaLubbaDubDubDev** [comment]
> ![image](https://github.com/user-attachments/assets/7f214b0a-64c2-45c1-ac6f-5aa4f9ae2fd2)
> 

The NotPixel developers have switched canvas loading to WebSockets instead of regular HTTP requests. So far, I haven't been able to resolve this issue. This is an important part of my script's architecture as it directly influences the mechanism for selecting unpainted pixels. I checked other developers' scripts whose bots are still working, and they either don't have a mechanism for matching the template with the canvas and identifying unpainted pixels, or it's disabled by default. Instead, they choose a random pixel. This method is less accurate but functional. I will now add random pixel selection to my script; it's more of a temporary fix than a proper solution, but it works. Additionally, I will expand the range of templates to choose even less popular ones, which should increase the chances of getting a reward.

**Comment by WubbaLubbaDubDubDev** [comment]
@SeiZ28 

As a temporary solution, I have added an option for random pixel selection until I find a more appropriate solution to the problem. I recommend keeping the new parameter RANDOM_PIXEL_MODE set to True.

**Comment by SeiZ28** [comment]
Thanks for the update, but there are new errors
![image](https://github.com/user-attachments/assets/da0e1810-4e85-4692-87bb-c28aff91a490)

**Comment by SeiZ28** [comment]
Have you fixed the canvas loading issue, or do you still need to use randomization?

**Comment by WubbaLubbaDubDubDev** [comment]
> Have you fixed the canvas loading issue, or do you still need to use randomization?

I'm still working on it.

**Comment by WubbaLubbaDubDubDev** [comment]
@SeiZ28 
HEEL YRAH

![IMG_20241115_121216_740.jpg](https://github.com/user-attachments/assets/4239cc10-582a-49e4-8c32-bce6f69fad7e)

![IMG_20241115_121401_062.jpg](https://github.com/user-attachments/assets/fc83fdfc-bb1a-4913-9ab9-fb05c6f35a37)

**Comment by WubbaLubbaDubDubDev** [comment]
> Have you fixed the canvas loading issue, or do you still need to use randomization?
The issue has been resolved
