### ISSUE TITLE
[enhancement] Secret word sniping

### ISSUE THREAD

**Issue by AKASH-UWU** [WubbaLubbaDubDubDev/notpixel_bot_advanced#17]
Make a function to solve secret words, dynamically fetching might be better!

**Comment by WubbaLubbaDubDubDev** [comment]
> Make a function to solve secret words, dynamically fetching might be better!

Great idea, I will consider ways to implement it

**Comment by WubbaLubbaDubDubDev** [comment]
> Make a function to solve secret words, dynamically fetching might be better!

I have partially implemented the proposed functionality, but currently, the secret words need to be manually specified in the env file.
