### ISSUE TITLE
 ERROR    | 625 - 17 | Unexpected error while downloading image | Attempt 1 | Sleep 2 sec | '__cf_bm'

### ISSUE THREAD

**Issue by GeRRyOD** [WubbaLubbaDubDubDev/notpixel_bot_advanced#19]
Hello! This error message is coming up for each session. Any solutions how to fix it? It's upgrading claiminig and etc, but can't download images 
 Unexpected error while downloading image | Attempt 1 | Sleep 2 sec | '__cf_bm'

**Comment by WubbaLubbaDubDubDev** [comment]
> Hello! This error message is coming up for each session. Any solutions how to fix it? It's upgrading claiminig and etc, but can't download images 
>  Unexpected error while downloading image | Attempt 1 | Sleep 2 sec | '__cf_bm'

That's strange, it seems like the __cf_bm cookie is not being stored on your end. Without it, template downloads usually don't work reliably. I will add a check to ensure its presence.
