### ISSUE TITLE
New error after notpixel update

### ISSUE THREAD

**Issue by SeiZ28** [WubbaLubbaDubDubDev/notpixel_bot_advanced#23]
![image](https://github.com/user-attachments/assets/d2038d27-4c38-46e0-8b29-23538277c00a)

**Comment by SeiZ28** [comment]
![image](https://github.com/user-attachments/assets/029469f2-6b8d-46b1-a16f-5e7481f822fa)

**Comment by WubbaLubbaDubDubDev** [comment]
> ![image](https://github.com/user-attachments/assets/029469f2-6b8d-46b1-a16f-5e7481f822fa)
> 

Have you updated the bot today?

I made two more commits today that fixed authentication issues that arose after the game's latest update.

**Comment by SeiZ28** [comment]
> > ![image](https://private-user-images.githubusercontent.com/69797793/386998697-029469f2-6b8d-46b1-a16f-5e7481f822fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MjY2MTksIm5iZiI6MTczMTkyNjMxOSwicGF0aCI6Ii82OTc5Nzc5My8zODY5OTg2OTctMDI5NDY5ZjItNmI4ZC00NmIxLWExNmYtNWU3NDgxZjgyMmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDEwMzgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0OTRkYWM4NTY4NTNmM2I0N2RjMTM4ZWJmNGNkNDk0OTU1OGUyY2JkODA4OWEzZTczMjIzOWI3YmU2NzJkMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KWmq3IXEmnpyEdyVivn4MV20LKq25mWPZAWXdxeDcEs)
> 
> Have you updated the bot today?
> 
> I made two more commits today that fixed authentication issues that arose after the game's latest update.

thx
