### ISSUE TITLE
Unknown error: Invalid URL: port can't be converted to integer

### ISSUE THREAD

**Issue by groovg** [WubbaLubbaDubDubDev/notpixel_bot_advanced#24]
Получаю этот еррор на некотррых аккаунтах при запуске, при том что прокси одинаковые (рези). Было бы круто ретраи повесить или пофиксить это в целом
![image](https://github.com/user-attachments/assets/b383beff-6787-4baf-9fc1-db692d2a3355)

**Comment by WubbaLubbaDubDubDev** [comment]
> Получаю этот еррор на некотррых аккаунтах при запуске, при том что прокси одинаковые (рези). Было бы круто ретраи повесить или пофиксить это в целом
> ![image](https://github.com/user-attachments/assets/b383beff-6787-4baf-9fc1-db692d2a3355)
> 

Доброго времени суток, я внёс ряд переработок в логике работы с прокси, скажите, присутствует ли описанная проблема в последнем обновлении?
