### ISSUE TITLE
Необходима помощь с прокси

### ISSUE THREAD

**Issue by madkite2** [WubbaLubbaDubDubDev/notpixel_bot_advanced#25]
Приветствую! Подскажите в чем может быть проблема, никак не хочет с прокси работать, ловлю ошибку
Please check your proxy settings! Прокси рабочие. Без прокси всё отлично работает.
![Безымянный](https://github.com/user-attachments/assets/de54be76-b23d-42d6-b884-5bbbd0c9209e)

**Comment by WubbaLubbaDubDubDev** [comment]
Сменил сервис geoip, обновите скрипт
