### ISSUE TITLE
обновление для турнира

### ISSUE THREAD

**Issue by SeiZ28** [WubbaLubbaDubDubDev/notpixel_bot_advanced#29]
Привет, как насчет того, чтобы заранее сделать версию скрипта для покраски турнирных шаблонов? Было бы очень кстати

**Comment by WubbaLubbaDubDubDev** [comment]
> Привет, как насчет того, чтобы заранее сделать версию скрипта для покраски турнирных шаблонов? Было бы очень кстати

Было бы, но пока даже у самой игре этот функционал не реализован, потому я могу только догадываться как там всё будет устроено в плане API

**Comment by WubbaLubbaDubDubDev** [comment]
> Привет, как насчет того, чтобы заранее сделать версию скрипта для покраски турнирных шаблонов? Было бы очень кстати

Реализовал подписку на турнирные шаблоны, можно активировать эту функцию в bot/config/config.py. На данный момент не вижу смысла этого функционала, но возможно он пригодится в следующих обновлениях игры, когда разработчики запилят функционал по взаимодействию с турнирным шаблонами

**Comment by SeiZ28** [comment]
> > Привет, как насчет того, чтобы заранее сделать версию скрипта для покраски турнирных шаблонов? Было бы очень кстати
> 
> Реализовал подписку на турнирные шаблоны, можно активировать эту функцию в bot/config/config.py. На данный момент не вижу смысла этого функционала, но возможно он пригодится в следующих обновлениях игры, когда разработчики запилят функционал по взаимодействию с турнирным шаблонами

Привет, сегодня обещают открыть турнир, буду пробовать твой апдейт

**Comment by WubbaLubbaDubDubDev** [comment]
> > > Привет, как насчет того, чтобы заранее сделать версию скрипта для покраски турнирных шаблонов? Было бы очень кстати
> > 
> > Реализовал подписку на турнирные шаблоны, можно активировать эту функцию в bot/config/config.py. На данный момент не вижу смысла этого функционала, но возможно он пригодится в следующих обновлениях игры, когда разработчики запилят функционал по взаимодействию с турнирным шаблонами
> 
> Привет, сегодня обещают открыть турнир, будем ждать

На самом деле, пробовать там особо нечего, реализована только подписка на шаблоны, так как API контроллеры которые отвечают за это уже известны. Подписка вроде бы как работает но контроллер не возвращает ни координат ни ссылку на изображение. Как будет всё реализовано в игре, допилю до конца. По факту я лишь заготовку сделал
