### ISSUE TITLE
implement refresh 

### ISSUE THREAD

**Issue by darkPrince74** [WubbaLubbaDubDubDev/notpixel_bot_advanced#3]
hi frist of all thanks for your script modifications and Commitments. It's cool

the bot sometime shows errors when when servers overloads. recently it shows repaint error "unauthorized" 

please modify script to hit refresh when errors like that appears. it fails to paint and claim but goes to sleep

**Comment by WubbaLubbaDubDubDev** [comment]
> hi frist of all thanks for your script modifications and Commitments. It's cool
> 
> the bot sometime shows errors when when servers overloads. recently it shows repaint error "unauthorized" 
> 
> please modify script to hit refresh when errors like that appears. it fails to paint and claim but goes to sleep 



I’ve added a new feature for selecting a less popular template, which significantly increases the chances of getting triple rewards.

Regarding the errors, particularly the "unauthorized" issue that occurs when the servers are overloaded: the automatic sleep after errors has been disabled. This approach worked well when errors were rare, but now, with sessions frequently ending before the timer is up, it causes more problems. Now, if two request attempts fail, the current function terminates before the next cycle. This has proven to be the most effective approach from all that I've tested.

Looking forward to your feedback!

**Comment by darkPrince74** [comment]
thank you very much for explaining the issues and updating the bot!  I've just tested and it seems way better than before!  I'll attach all my session and leave it working now to see how it goes. I'm glad to hear from you! thanks again
