### ISSUE TITLE
Error : https://notpx.app/api/v1/offer/check

### ISSUE THREAD

**Issue by ape3xdiem** [WubbaLubbaDubDubDev/notpixel_bot_advanced#30]
ERROR    | 1234 - 4 | Unknown error: 403, message='Forbidden', url=URL('https://notpx.app/api/v1/offer/check')

Then sleep

**Comment by WubbaLubbaDubDubDev** [comment]
>  ERROR    | 1234 - 4 | Unknown error: 403, message='Forbidden', url=URL('https://notpx.app/api/v1/offer/check')
> 
> Then sleep

Try updating the script. I’ve made some adjustments to address your situation.

**Comment by ape3xdiem** [comment]
Thanks for quick action

bu still continue
 ERROR    | 1236 - 1 | Unknown error: 403, message='Forbidden', url=URL('https://notpx.app/api/v1/offer/check')

As a workaround, I disable the relevant lines and run normally

     # await self.check_response(http_client=http_client)
and 
    # async def check_response(self, http_client):
    #    headers_ = copy.deepcopy(headers_check)
    #    headers_['User-Agent'] = self.user_agent
    #    response = await http_client.post("https://notpx.app/api/v1/offer/check", headers=headers_)
    #    response.raise_for_status()

**Comment by prognt** [comment]
same

**Comment by WubbaLubbaDubDubDev** [comment]
> same

Today, I was researching the game and noticed that during the launch, it makes a request to the check controller. I decided to add this request to the bot to make it mimic the game's behavior as closely as possible in terms of requests. However, it seems that not everyone’s game makes a check request. In your case, during the request, you are getting a "403 Forbidden" response, meaning access is denied.

**Comment by Kravt48** [comment]
same error, how to fix it?

**Comment by WubbaLubbaDubDubDev** [comment]
> same error, how to fix it?

fixed
