### ISSUE TITLE
Confirmation Code Sent Error

### ISSUE THREAD

**Issue by AKa0258** [WubbaLubbaDubDubDev/notpixel_bot_advanced#36]
Confirmation code not coming, i tried different accounts and with different id and hash still not coming. 
![image](https://github.com/user-attachments/assets/e2bd9f16-72f4-49e1-8ac3-d85bb713e558)

**Comment by WubbaLubbaDubDubDev** [comment]
@AKa0258 
It's most likely an issue on Telegram's side. Please try again later.
