### ISSUE TITLE
покраска пикселей теперь через вебсокет

### ISSUE THREAD

**Issue by SeiZ28** [WubbaLubbaDubDubDev/notpixel_bot_advanced#41]
![image](https://github.com/user-attachments/assets/86f537fa-c71a-486b-83e3-fd9163e74ee8)
бот теперь не работает, так как разработчики сделали покраску через вебсокет, с которого качается холст

**Comment by WubbaLubbaDubDubDev** [comment]
> ![image](https://github.com/user-attachments/assets/86f537fa-c71a-486b-83e3-fd9163e74ee8)
> бот теперь не работает, так как разработчики сделали покраску через вебсокет, с которого качается холст

☠️

**Comment by SeiZ28** [comment]
Я к сожалению отлетел в теневой бан со всех аккаунтов

**Comment by danazor** [comment]
> Я к сожалению отлетел в теневой бан со всех аккаунтов

Как вы поняли теневой бан?

**Comment by WubbaLubbaDubDubDev** [comment]
> Я к сожалению отлетел в теневой бан со всех аккаунтов

Сам в бане.

**Comment by WubbaLubbaDubDubDev** [comment]
> > Я к сожалению отлетел в теневой бан со всех аккаунтов
> 
> Как вы поняли теневой бан?
После перезагрузки страницы все изменения на холсте исчезают, энергия восстанавливается

**Comment by WubbaLubbaDubDubDev** [comment]
@SeiZ28 
Что касаемо фикса на рисовку. Он уже есть, я обновление выпущу. Правда, могут быть проблемы с отображением награды. Раньше баланс с награды возвращался в ответ на запрос отвечающий за рисование. Сейчас такого нету. Награда будет рассчитываться как разница балансов до и после рисования, что не всегда работает корректно, из-за задержек в обновлении баланса.

**Comment by SeiZ28** [comment]
> > Я к сожалению отлетел в теневой бан со всех аккаунтов
> 
> Как вы поняли теневой бан?

Не засчитывает пиксели

**Comment by SeiZ28** [comment]
> > Я к сожалению отлетел в теневой бан со всех аккаунтов
> 
> Сам в бане.

Анлак

**Comment by SeiZ28** [comment]
> @SeiZ28 Что касаемо фикса на рисовку. Он уже есть, я обновление выпущу. Правда, могут быть проблемы с отображением награды. Раньше баланс с награды возвращался в ответ на запрос отвечающий за рисование. Сейчас такого нету. Награда будет рассчитываться как разница балансов до и после рисования, что не всегда работает корректно, из-за задержек в обновлении баланса.

Спасибо конечно, но будем ждать, может удалят из теневого бана
