### ISSUE TITLE
Unexpected error while dowloading image

### ISSUE THREAD

**Issue by Zifirlk** [WubbaLubbaDubDubDev/notpixel_bot_advanced#43]
![image](https://github.com/user-attachments/assets/43c41eba-975e-4a5a-bd2c-64dd052d1606)

how to fix it?

**Comment by WubbaLubbaDubDubDev** [comment]
> ![image](https://github.com/user-attachments/assets/43c41eba-975e-4a5a-bd2c-64dd052d1606)
> 
> how to fix it?

``git pull``
