### ISSUE TITLE
3x not working and giving 0

### ISSUE THREAD

**Issue by itsAmiraly** [WubbaLubbaDubDubDev/notpixel_bot_advanced#5]
![Screenshot 2024-10-17 012104](https://github.com/user-attachments/assets/f555eea9-d81e-4428-a5c7-02e39b1d2d38)

**Comment by WubbaLubbaDubDubDev** [comment]
> ![Screenshot 2024-10-17 012104](https://github.com/user-attachments/assets/f555eea9-d81e-4428-a5c7-02e39b1d2d38)
> 
It seems to be an issue on notpixel's end, as I also wasn’t getting the 3x between 10:00 PM and 7:00 AM. However, everything is functioning normally now, and I'll continue monitoring the situation.

**Comment by WubbaLubbaDubDubDev** [comment]
![Screenshot_20241017-075607.png](https://github.com/user-attachments/assets/5ba15dda-88f7-4feb-bf47-035ec214d4d4)
