### ISSUE TITLE
Tell

### ISSUE THREAD

**Issue by fIne123333** [WubbaLubbaDubDubDev/notpixel_bot_advanced#9]
![5246834467039996469](https://github.com/user-attachments/assets/152fba2f-a40b-451c-bfde-075938f749d5)

Hello! Please give me an example of how this should be driven in full form.

**Comment by WubbaLubbaDubDubDev** [comment]
> Hello! Please give me an example of how this should be driven in full form.

![image](https://github.com/user-attachments/assets/1cd30891-8240-4805-b309-137dba4be695)
Something like this. This is my configuration, lists should be written in a single line without wrapping.
But it's not necessary to fill in all the fields; only API_ID and API_HASH are sufficient.
